### ISSUE TITLE
Consider using tags

### ISSUE THREAD

**Issue by jonasbn** [Bahjat/pre-commit-golang#6]
When using these hooks the following is emitted by `pre-commit`

```
[WARNING] The 'rev' field of repo 'git://github.com/Bahjat/pre-commit-golang' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
```

Please consider using tags adhering to the recommendations in the pre-commit [documentation](https://pre-commit.com/#using-the-latest-version-for-a-repository).

**Comment by Bahjat** [comment]
done with the following commit https://github.com/Bahjat/pre-commit-golang/commit/cc377874ca0f47b9eaf0e2f9f13d2488b2163256
